const items=[
{name:"Interstellar",type:"Movies",genre:"Sci-Fi",rating:"8.7",year:"2014",why:"For ambitious sci-fi, emotional storytelling and unforgettable worlds.",desc:"A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",tags:["Sci-Fi","Drama","Adventure"]},
{name:"Severance",type:"TV Shows",genre:"Thriller",rating:"8.7",year:"2022",why:"For mysterious worlds, slow-burn tension and razor-sharp ideas.",desc:"Employees undergo a procedure that divides their work and personal memories.",tags:["Thriller","Mystery","Drama"]},
{name:"The Silent Patient",type:"Books",genre:"Thriller",rating:"4.4",year:"2019",why:"A gripping psychological mystery with twists worth chasing.",desc:"A famous painter stops speaking after a shocking crime, and a therapist becomes determined to uncover why.",tags:["Thriller","Mystery","Psychology"]},
{name:"Dune: Part Two",type:"Movies",genre:"Sci-Fi",rating:"8.5",year:"2024",why:"Epic scale, political intrigue and spectacular world-building.",desc:"Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family.",tags:["Sci-Fi","Drama","Epic"]},
{name:"Dark",type:"TV Shows",genre:"Sci-Fi",rating:"8.7",year:"2017",why:"For puzzle-box storytelling, time travel and a deeply atmospheric mystery.",desc:"A missing child sets four families on a frantic search for answers spanning generations.",tags:["Sci-Fi","Mystery","Drama"]},
{name:"Piranesi",type:"Books",genre:"Drama",rating:"4.6",year:"2020",why:"Strange, beautiful and immersive—perfect for readers who like the unexpected.",desc:"A man lives in a mysterious infinite house filled with statues, tides and secrets.",tags:["Fantasy","Mystery","Literary"]},
{name:"Arrival",type:"Movies",genre:"Sci-Fi",rating:"8.0",year:"2016",why:"Thoughtful science fiction with emotion, language and big questions.",desc:"A linguist works to communicate with mysterious visitors from another world.",tags:["Sci-Fi","Drama","Mystery"]},
{name:"Mindhunter",type:"TV Shows",genre:"Thriller",rating:"8.6",year:"2017",why:"For intelligent crime stories, unsettling psychology and brilliant dialogue.",desc:"FBI agents develop criminal profiling by studying the minds of notorious killers.",tags:["Crime","Thriller","Drama"]}
];
let selectedType="All", selectedGenre="All";
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function card(x){return '<article class="card" data-name="'+esc(x.name)+'"><div class="poster"><span class="type">'+x.type+'</span><span class="initial">'+esc(x.name[0])+'</span></div><div class="info"><h3>'+esc(x.name)+' <span class="rating">★ '+x.rating+'</span></h3><div class="meta">'+x.year+' · '+x.genre+'</div><p class="why">'+esc(x.why)+'</p></div></article>'}
function render(){let q=document.querySelector("#search").value.toLowerCase();let filtered=items.filter(x=>(selectedType==="All"||x.type===selectedType)&&(selectedGenre==="All"||x.genre===selectedGenre)&&(!q||x.name.toLowerCase().includes(q)||x.genre.toLowerCase().includes(q)));document.querySelector("#recommendations").innerHTML=filtered.slice(0,4).map(card).join("")||'<p style="color:#999">No matches yet. Try another title or genre.</p>';document.querySelector("#trendingGrid").innerHTML=items.slice(3,7).map(card).join("");document.querySelector("#gemsGrid").innerHTML=items.slice(1,5).map(card).join("");document.querySelectorAll(".card").forEach(c=>c.onclick=()=>openModal(items.find(x=>x.name===c.dataset.name)))} 
function openModal(x){document.querySelector("#modalBody").innerHTML='<div class="eyebrow">'+x.type+' · '+x.year+'</div><h2>'+esc(x.name)+'</h2><div class="tags">'+x.tags.map(t=>'<span class="tag">'+esc(t)+'</span>').join("")+'</div><p>'+esc(x.desc)+'</p><strong>★ '+x.rating+' / 10</strong><p><b>Why you’ll like it:</b> '+esc(x.why)+'</p>';document.querySelector("#modal").classList.add("open")}
document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedType=b.dataset.type;render()});
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedGenre=b.textContent;render()});
document.querySelector("#search").oninput=render;document.querySelector("#recommendBtn").onclick=()=>document.querySelector("#discover").scrollIntoView({behavior:"smooth"});
document.querySelector("#close").onclick=()=>document.querySelector("#modal").classList.remove("open");document.querySelector("#modal").onclick=e=>{if(e.target.id==="modal")e.currentTarget.classList.remove("open")};
document.querySelector("#themeBtn").onclick=()=>document.body.classList.toggle("light");render();